"use client"
import './globals.css';
import ReactQueryProvider from "./ReactQueryProvider";
import {RecoilRoot} from "recoil";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <RecoilRoot>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </RecoilRoot>
      </body>
    </html>
  )
}
